[package]
name = "counter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "counter"
crate-type = ["cdylib", "lib"]

[dependencies]
bs58 = "0.5.1"
solana-program = "=1.17.17"
